import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import ProtectedRoute from "@/lib/providers/ProtectedRoute";
import Navbar from "@/components/common/navbar";
import { Toaster } from "react-hot-toast";
import StoreProvider from "@/lib/store/store-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen w-screen overflow-x-hidden`}
      >
        <StoreProvider>
          <ProtectedRoute>
            <div className="h-full min-h-screen w-full overflow-x-hidden relative">
              {children}
              <Toaster />
            </div>
          </ProtectedRoute>
        </StoreProvider>
      </body>
    </html>
  );
}
